# Generated by Django 2.0.2 on 2019-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id_discount_coupon', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('code_coupons', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount_applied', models.IntegerField()),
            ],
            options={
                'db_table': 'discount_coupon',
            },
        ),
    ]
